### ISSUE TITLE
Table login events not recorded

### ISSUE THREAD

**Issue by BrianSChristian** [ctsit/shibboleth_and_table_auth#17]
Running REDCap 9.3.4 and Shibboleth 3.0.4 and this patch.  When authentication method is set to table+Shibboleth and user logs in with table, the redcap_log_view table does not record event LOGIN_SUCCESS or LOGIN_FAILURE.  These events are recorded when the authentication method is set to table.

**Comment by pbchase** [comment]
@ChemiKyle, I know what @BrianSChristian is talking about. Shib logins can't record those events, but table logins always should. I marked this as a bug.

**Comment by ChemiKyle** [comment]
@BrianSChristian Thank you for reporting this! I was able to fix this issue just now in a test environment, I will begin the process for a new patch tomorrow.
